# Generated by Django 4.1.6 on 2023-03-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_locatin',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.CreateModel(
            name='Permission_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission_level', models.IntegerField(default=1)),
                ('profile_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='accounts.profile')),
                ('profile_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='accounts.profile')),
            ],
        ),
    ]
